### ISSUE TITLE
User Story: System register 1.1

### ISSUE THREAD

**Issue by onur-CK** [onur-CK/SkillFlow#1]
#### [US-1.1] As a **user**, I can **register to the system** so that **I can access the platform's features**.

**Acceptance Criteria:**
- The user should be able to register using an email and password.  
- The password must be at least 8 characters long.  
- The email format should be validated.  
- Users cannot register with an email that is already in use.  

**Tasks:**
- [x] Create the Django User model.  
- [x] Design the registration form.  
- [x] Add form validation.  
- [x] Implement the registration view.  
- [x] Add redirection after successful registration.
