### ISSUE TITLE
User Story: Virtual Environment. 5.2

### ISSUE THREAD

**Issue by onur-CK** [onur-CK/SkillFlow#27]
#### [US-5.2] 
As a **developer**, I can **set up a virtual environment using `venv`** so that **I can isolate project dependencies**.  

**Acceptance Criteria:**  
- The virtual environment is created in the project directory.  
- The virtual environment is activated before installing dependencies.  

**Tasks:**  
- [x] Run the command `python -m venv venv` in the project folder.  
- [x] Activate the virtual environment (`source venv/bin/activate` on Mac/Linux, `venv\Scripts\activate` on Windows).  
- [x] Add `venv` to `.gitignore`.
